###
POST http://localhost:9000/api/users HTTP/1.1
Content-Type: application/json

{
    "name": "Guido van Rossum",
    "age": 67,
    "email": "guido_van@gmail.com"
}

###
GET http://localhost:9000/api/users HTTP/1.1

###
GET http://localhost:9000/api/users/63fe9e174eeea9774fb3a92f HTTP/1.1

###

PUT http://localhost:9000/api/users/63fe9e174eeea9774fb3a92f HTTP/1.1
Content-Type: application/json

{
    "name": "Alan Turing ",
    "age": 42,
    "email": "alan_turing@gmail.com"
}

###
DELETE http://localhost:9000/api/users/63fea51b1766fd48c30ebcc7 HTTP/1.1
